# Generated by Django 5.1.1 on 2025-01-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esppayload',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='M-Pesa Receipt'),
        ),
        migrations.AddField(
            model_name='esppayload',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Transaction Date'),
        ),
        migrations.AddField(
            model_name='esppayload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='esppayload',
            name='amount',
            field=models.CharField(max_length=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='esppayload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='esppayload',
            name='fuel',
            field=models.CharField(max_length=10, verbose_name='Fuel Type'),
        ),
        migrations.AlterField(
            model_name='esppayload',
            name='fuelstation',
            field=models.CharField(max_length=50, verbose_name='Fuel Station'),
        ),
        migrations.AlterField(
            model_name='esppayload',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
    ]
