# Generated by Django 5.1.1 on 2025-01-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_customuser_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esppayload',
            name='fuel',
            field=models.CharField(),
        ),
    ]
